# -*- coding: utf-8 -*-
"""band_calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CygYQa6gEPfar73VlFTc76yykgzopD9I
"""

import math

def estimate_band_size(ladder_sizes, ladder_distances, sample_distance):
    log_sizes = [math.log10(size) for size in ladder_sizes]

    n = len(ladder_distances)
    x_mean = sum(ladder_distances) / n
    y_mean = sum(log_sizes) / n

    numerator = sum((x - x_mean) * (y - y_mean) for x, y in zip(ladder_distances, log_sizes))
    denominator = sum((x - x_mean) ** 2 for x in ladder_distances)

    slope = numerator / denominator
    intercept = y_mean - slope * x_mean

    predicted_log_size = slope * sample_distance + intercept
    predicted_size = 10 ** predicted_log_size

    return predicted_size

def main():
    print("Gel Band Size Calculator")
    print("------------------------")

    ladder_sizes = list(map(float, input("Enter ladder band sizes (bp), separated by commas: ").split(",")))
    ladder_distances = list(map(float, input("Enter ladder migration distances, separated by commas: ").split(",")))
    sample_distance = float(input("Enter sample band migration distance: "))

    if len(ladder_sizes) != len(ladder_distances):
        print("Error: ladder sizes and distances must have the same number of values.")
        return

    estimated_size = estimate_band_size(ladder_sizes, ladder_distances, sample_distance)
    print(f"Estimated sample band size: {estimated_size:.2f} bp")

if __name__ == "__main__":
    main()